"""Make base_url nullable in companies table

Revision ID: f4182e0ce094
Revises: f4629a4a684e
Create Date: 2024-11-19 17:42:26.188254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f4182e0ce094'
down_revision: Union[str, None] = 'f4629a4a684e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'base_url',
               existing_type=sa.String(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.alter_column('companies', 'base_url',
               existing_type=sa.String(length=255),
               nullable=False)
    # ### commands auto generated by Alembic - please adjust! ###
